### ISSUE TITLE
Rejected: would clobber existing tag

### ISSUE THREAD

**Issue by idanl-spearuav** [brettdorrans/write-version-to-file#3]
When I tried to use this action I received this error
`! [rejected] v0.3 -> v0.3 (would clobber existing tag)`
(no matter which tag I try)
adding -f like this solved it for me
`git fetch --tags -f`
I was unable to open a PR with this solution.

**Comment by brettdorrans** [comment]
@idanl-spearuav thanks for reporting, I will fix and release a new version.
