### ISSUE TITLE
Write to an external repo

### ISSUE THREAD

**Issue by thecem** [brettdorrans/write-version-to-file#7]
Is it possible to write to external
Repo file?
Where only one variable in the file is changed?

**Comment by brettdorrans** [comment]
@thecem I'm not sure this would be easy to do from within a GitHub action, it will probably depend on how your repositories are set up. If they're public repositories it may be possible, but if they're private or restrict who can push to branches it may be tricky.

At the moment this action doesn't support such a feature and I don't have any plans for it. If you find a solution to your question feel free to open a PR.
